version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: ./deploy/dev/Dockerfile_app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    tty: true

  redis:
    container_name: redis
    hostname: redis
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
